/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.C_Inmuebles;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author wdg20
 */
public class V_EditarInmueble extends javax.swing.JFrame {

    C_Inmuebles cu;

    /**
     * Creates new form V_EditarInmueble
     */
    public V_EditarInmueble() {
        initComponents();
        cu = new C_Inmuebles();
        cu.setIu_EditarInmueble(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        E_BtnAgregar = new javax.swing.JButton();
        E_TipoInmueble = new javax.swing.JComboBox<>();
        E_TipoProceso = new javax.swing.JComboBox<>();
        E_Estado = new javax.swing.JComboBox<>();
        E_AreaInmueble = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        E_CantidadPisos = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        E_Direccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        E_Precio = new javax.swing.JTextField();
        E_AgenteEncargado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        E_CantidadHabitaciones = new javax.swing.JTextField();
        E_Fecha = new com.toedter.calendar.JDateChooser();
        E_CantidadBaños = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        E_Descripcion = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        E_Identificador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel10.setText("Cantidad de Habitaciones:");

        jLabel11.setText("Cantidad de Baños:");

        jLabel12.setText("Cantidad de Pisos:");

        jLabel13.setText("Dirección:");

        E_BtnAgregar.setText("GUARDAR");
        E_BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_BtnAgregarActionPerformed(evt);
            }
        });

        E_TipoInmueble.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Apartamento", "Lote", "Finca", "Local" }));

        E_TipoProceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta", "Alquiler" }));

        E_Estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("EDITAR INMUEBLE");

        jLabel2.setText("Tipo de Proceso:");

        jLabel3.setText("Precio:");

        jLabel4.setText("Estado:");

        jLabel5.setText("Fecha ");

        jLabel6.setText("Agente Encargado:");

        jLabel7.setText("Descripción: ");

        jLabel8.setText("Tipo de Inmueble: ");

        E_Fecha.setDateFormatString("d/MM/y ");

        E_Descripcion.setColumns(20);
        E_Descripcion.setRows(5);
        jScrollPane1.setViewportView(E_Descripcion);

        jLabel9.setText("Area de Inmueble:");

        jLabel14.setText("Identificador:");

        E_Identificador.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel13))
                                                .addGap(18, 18, 18))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addGap(55, 55, 55)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(E_TipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(E_CantidadPisos, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                                .addComponent(E_CantidadBaños)
                                                .addComponent(E_AreaInmueble)
                                                .addComponent(E_CantidadHabitaciones)
                                                .addComponent(E_Direccion)))))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(E_Precio)
                                    .addComponent(E_TipoProceso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(E_Estado, 0, 150, Short.MAX_VALUE)
                                    .addComponent(E_AgenteEncargado)
                                    .addComponent(E_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(E_Identificador))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(E_BtnAgregar)
                        .addGap(0, 39, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(256, 256, 256))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(E_TipoProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(E_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(E_TipoInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(E_AreaInmueble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(E_CantidadHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(E_CantidadBaños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_CantidadPisos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel6)
                    .addComponent(E_AgenteEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(E_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(E_Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(E_BtnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setIdentificador(String i) {
        E_Identificador.setText(i);
    }

    public void setTipoInmueble(String i) {
        E_TipoInmueble.setSelectedItem(i);
    }

    public void setAreaInmueble(String i) {
        E_AreaInmueble.setText(i);
    }

    public void setCantidadHabitaciones(String i) {
        E_CantidadHabitaciones.setText(i);
    }

    public void setCantidadBaños(String i) {
        E_CantidadBaños.setText(i);
    }

    public void setCantidadPisos(String i) {
        E_CantidadPisos.setText(i);
    }

    public void setDireccion(String i) {
        E_Direccion.setText(i);
    }

    public void setTipoProceso(String i) {
        E_TipoProceso.setSelectedItem(i);
    }

    public void setPrecio(String i) {
        E_Precio.setText(i);
    }

    public void setEstado(String i) {
        E_Estado.setSelectedItem(i);
    }

    public void setFechaVentaAlquiler(String i) {
        E_Fecha.setDateFormatString(i);
    }

    public void setAgenteEncargado(String i) {
        E_AgenteEncargado.setText(i);
    }

    public void setDescripcion(String i) {
        E_Descripcion.setText(i);
    }

    public String getTipoInmueble() {
        return E_TipoInmueble.getSelectedItem().toString();
    }

    public String getAreaInmueble() {
        return E_AreaInmueble.getText();
    }

    public String getCantidadHabitaciones() {
        return E_CantidadHabitaciones.getText();
    }

    public String getCantidadBaños() {
        return E_CantidadBaños.getText();
    }

    public String getCantidadPisos() {
        return E_CantidadPisos.getText();
    }

    public String getDireccion() {
        return E_Direccion.getText();
    }

    public String getTipoProceso() {
        return E_TipoProceso.getSelectedItem().toString();
    }

    public String getPrecio() {
        return E_Precio.getText();
    }

    public String getEstado() {
        return E_Estado.getSelectedItem().toString();
    }

    public String getFechaVentaAlquiler() {
        return E_Fecha.getDate().toString();
    }

    public String getAgenteEncargado() {
        return E_AgenteEncargado.getText();
    }

    public String getDescripcion() {
        return E_Descripcion.getText();
    }

    public String getIdentificador() {
        return E_Identificador.getText();
    }


    private void E_BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_BtnAgregarActionPerformed
        if (E_AreaInmueble.getText().isEmpty() || E_CantidadHabitaciones.getText().isEmpty()
                || E_CantidadBaños.getText().isEmpty() || E_CantidadPisos.getText().isEmpty()
                || E_Direccion.getText().isEmpty() || E_Precio.getText().isEmpty() || E_AgenteEncargado.getText().isEmpty()
                || E_Descripcion.getText().isEmpty() || E_Fecha.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar");

        } else if (JOptionPane.showConfirmDialog(null, "Se actualizara el registro, ¿desea continuar?") == JOptionPane.YES_OPTION) {
            cu.ActualizarInmueble();
            this.dispose();
        }

    }//GEN-LAST:event_E_BtnAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_EditarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_EditarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_EditarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_EditarInmueble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_EditarInmueble().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField E_AgenteEncargado;
    private javax.swing.JTextField E_AreaInmueble;
    private javax.swing.JButton E_BtnAgregar;
    private javax.swing.JTextField E_CantidadBaños;
    private javax.swing.JTextField E_CantidadHabitaciones;
    private javax.swing.JTextField E_CantidadPisos;
    private javax.swing.JTextArea E_Descripcion;
    private javax.swing.JTextField E_Direccion;
    private javax.swing.JComboBox<String> E_Estado;
    private com.toedter.calendar.JDateChooser E_Fecha;
    private javax.swing.JTextField E_Identificador;
    private javax.swing.JTextField E_Precio;
    private javax.swing.JComboBox<String> E_TipoInmueble;
    private javax.swing.JComboBox<String> E_TipoProceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
