/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.C_Inmuebles;
import Controlador.C_Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author GUSTAVO RAMIREZ
 */
public class V_EditarUsuario extends javax.swing.JFrame {

    C_Usuario cu;

    /**
     * Creates new form V_EditarUsuario
     */
    public V_EditarUsuario() {
        initComponents();
        cu = new C_Usuario();
        cu.setIu_EditarUsuario(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        E_Correo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        E_TipoUsuario = new javax.swing.JComboBox<>();
        E_Contraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        E_BtnRegistrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        E_Nombre = new javax.swing.JTextField();
        E_Apellido = new javax.swing.JTextField();
        E_Documento = new javax.swing.JTextField();
        E_Telefono = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        E_Identificador = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("EDITAR USUARIO");

        jLabel4.setText("Documento:");

        jLabel8.setText("Contraseña:");

        jLabel2.setText("Nombre: ");

        jLabel5.setText("Teléfono");

        E_TipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Agente", "Administrador " }));

        E_Contraseña.setEditable(false);

        jLabel3.setText("Apellido: ");

        jLabel6.setText("Correo: ");

        E_BtnRegistrar.setText("GUARDAR");
        E_BtnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_BtnRegistrarActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de Usuario: ");

        jLabel14.setText("Identificador:");

        E_Identificador.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(E_BtnRegistrar)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(E_Contraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(E_TipoUsuario, 0, 165, Short.MAX_VALUE)
                                    .addComponent(E_Identificador, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(E_Correo, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                                    .addComponent(E_Telefono)
                                    .addComponent(E_Documento)
                                    .addComponent(E_Nombre)
                                    .addComponent(E_Apellido)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel1)))
                .addGap(37, 47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(E_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(E_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(E_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(E_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(E_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(E_TipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(E_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(E_Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(E_BtnRegistrar)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void E_BtnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_BtnRegistrarActionPerformed
        // CODIGO PARA EL BOTON REGISTRARSE

        if (E_Nombre.getText().isEmpty() || E_Apellido.getText().isEmpty()
                || E_Documento.getText().isEmpty() || E_Telefono.getText().isEmpty()
                || E_Correo.getText().isEmpty() || E_Contraseña.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar");

        } else if (JOptionPane.showConfirmDialog(null, "Se actualizara el registro, ¿desea continuar?") == JOptionPane.YES_OPTION) {
            cu.ActualizarUsuario();
            this.dispose();
        }
    }//GEN-LAST:event_E_BtnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_EditarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_EditarUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField E_Apellido;
    private javax.swing.JButton E_BtnRegistrar;
    private javax.swing.JPasswordField E_Contraseña;
    private javax.swing.JTextField E_Correo;
    private javax.swing.JTextField E_Documento;
    private javax.swing.JTextField E_Identificador;
    private javax.swing.JTextField E_Nombre;
    private javax.swing.JTextField E_Telefono;
    private javax.swing.JComboBox<String> E_TipoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    public void setIdentificador(String i) {
        E_Identificador.setText(i);
    }

    public void setNombre(String i) {
        E_Nombre.setText(i);
    }

    public void setApellido(String i) {
        E_Apellido.setText(i);
    }

    public void setDocumento(String i) {
        E_Documento.setText(i);
    }

    public void setCorreo(String i) {
        E_Correo.setText(i);
    }

    public void setTelefono(String i) {
        E_Telefono.setText(i);
    }

    public void setTipoUsuario(String i) {
        E_TipoUsuario.setSelectedItem(i);
    }

    public void setContraseña(String i) {
        E_Contraseña.setText(i);
    }

    public String getIdentificador() {
        return E_Identificador.getText();
    }

    public String getDocumento() {
        return E_Documento.getText();
    }

    public String getNombre() {
        return E_Nombre.getText();
    }

    public String getApellido() {
        return E_Apellido.getText();
    }

    public String getCorreo() {
        return E_Correo.getText();
    }

    public String getTelefono() {
        return E_Telefono.getText();
    }

    public String getTipoUsuario() {
        return E_TipoUsuario.getSelectedItem().toString();
    }

    public String getContraseña() {
        return E_Contraseña.getText();

    }
}
