/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.C_Inmuebles;
import Controlador.C_Usuario;
import Modelo.M_Inmuebles;
import Modelo.M_Usuario;
import Utilidades.ConexionBD;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author GUSTAVO RAMIREZ
 */
public class V_GestionUsuario extends javax.swing.JPanel {

    String Columna[] = {"ID", "Nombre", "Apellido", "Documento", "Telefono", "Correo", "Tipo Usuario", "Contraseña"};
    DefaultTableModel Modelo = new DefaultTableModel(Columna, 0);
    C_Usuario cu;
    M_Usuario bu;
    
    
    /**
     * Creates new form V_GestionUsuarios
     */
    public V_GestionUsuario() {
        initComponents();
        
        bu = new M_Usuario();
        cu = new C_Usuario();
        
        cu.setIu_GestionUsuarios(this);
        cu.ListarUsuarios();
    }
    
    public void AgregarFila(String datos[]) {
        Modelo.addRow(datos);

    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        G_Modificadores = new javax.swing.JPanel();
        G_BtnEditar1 = new javax.swing.JButton();
        G_BtnEliminar = new javax.swing.JButton();
        G_BtnActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        G_Tabla = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        G_Buscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        G_Filtro = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1356, 637));
        setPreferredSize(new java.awt.Dimension(1356, 637));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DE USUARIOS");

        G_Modificadores.setBorder(javax.swing.BorderFactory.createTitledBorder("Modificadores "));

        G_BtnEditar1.setText("Editar");
        G_BtnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_BtnEditar1ActionPerformed(evt);
            }
        });

        G_BtnEliminar.setText("Eliminar");
        G_BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout G_ModificadoresLayout = new javax.swing.GroupLayout(G_Modificadores);
        G_Modificadores.setLayout(G_ModificadoresLayout);
        G_ModificadoresLayout.setHorizontalGroup(
            G_ModificadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(G_ModificadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(G_BtnEditar1)
                .addGap(18, 18, 18)
                .addComponent(G_BtnEliminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        G_ModificadoresLayout.setVerticalGroup(
            G_ModificadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(G_ModificadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(G_ModificadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G_BtnEditar1)
                    .addComponent(G_BtnEliminar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        G_BtnActualizar.setText("Actualizar Tabla");
        G_BtnActualizar.setPreferredSize(new java.awt.Dimension(1356, 637));
        G_BtnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_BtnActualizarActionPerformed(evt);
            }
        });

        G_Tabla.setModel(Modelo);
        jScrollPane2.setViewportView(G_Tabla);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel3.setText("Filtro:");

        G_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_BuscarActionPerformed(evt);
            }
        });
        G_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                G_BuscarKeyReleased(evt);
            }
        });

        jLabel4.setText("Buscar:");

        G_Filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Identificador", "Nombre", "Apellido", "Documento", "Telefono", "Correo", "Tipo Usuario" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(G_Buscar)
                    .addComponent(G_Filtro, 0, 118, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(G_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("LISTADO DE USUARIOS: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(G_BtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(G_Modificadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(602, 602, 602))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(394, 394, 394)
                        .addComponent(jLabel1)))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(G_BtnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(G_Modificadores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void G_BtnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_BtnEditar1ActionPerformed
        //CODIGO AL PRESIONAR EL BOTON EDITAR INMUEBLE

        try {
            if (JOptionPane.showConfirmDialog(null, "Se editara el registro, ¿desea continuar?") == JOptionPane.YES_OPTION) {
                int Identificador;
                Identificador = Integer.parseInt(Modelo.getValueAt(G_Tabla.getSelectedRow(), 0).toString());

                cu.ConsultarUsuarioId(Identificador);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccion un registro para editar");
        }
    }//GEN-LAST:event_G_BtnEditar1ActionPerformed

    private void G_BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_BtnEliminarActionPerformed
        try {
            if (JOptionPane.showConfirmDialog(null, "Se eliminará el registro, ¿desea continuar?") == JOptionPane.YES_OPTION) {
                String Identificador = Modelo.getValueAt(G_Tabla.getSelectedRow(), 0).toString();
                ConexionBD c = new ConexionBD();
                boolean exito = false;
                String sql= "delete from usuarios where Identificador='" + Identificador + "'";
       
                try {
                    exito = c.ejecutarSql(sql);
                    c.cerrarConexion();
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error al cerrar la conexion");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccion un registro para eliminar");

        }
    }//GEN-LAST:event_G_BtnEliminarActionPerformed

    private void G_BtnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_BtnActualizarActionPerformed
        //CODIGO AL PRESIONAR EL BOTON ACTUALIZAR
        Modelo.setRowCount(0);
        cu.ListarUsuarios();

    }//GEN-LAST:event_G_BtnActualizarActionPerformed

    private void G_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_G_BuscarKeyReleased
        TableRowSorter<DefaultTableModel> Sorter;
        Sorter = new TableRowSorter<>(Modelo);
        G_Tabla.setRowSorter(Sorter);
        Sorter.setRowFilter(RowFilter.regexFilter(G_Buscar.getText(),G_Filtro.getSelectedIndex()));

    }//GEN-LAST:event_G_BuscarKeyReleased

    private void G_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_BuscarActionPerformed
//        // CODIGO AL PRESIONAR EL BOTON CREAR
//        V_Registro re = new V_Registro();
//        re.setVisible(true);
//        re.setLocationRelativeTo(this);

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton G_BtnActualizar;
    private javax.swing.JButton G_BtnEditar1;
    private javax.swing.JButton G_BtnEliminar;
    private javax.swing.JTextField G_Buscar;
    private javax.swing.JComboBox<String> G_Filtro;
    private javax.swing.JPanel G_Modificadores;
    public static javax.swing.JTable G_Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
