/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.C_Productos;
import Controlador.C_Cliente;
import Modelo.M_Productos;
import Utilidades.ConexionBD;
import Modelo.M_Cliente;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author wdg20
 */
public class V_GestionProductoCliente extends javax.swing.JPanel {

    String Columna[] = {"ID", "Nombre", "Precio", "Cantidad Disponible", "Descripcion", "Estado"};
    DefaultTableModel Modelo = new DefaultTableModel(Columna, 0);
    C_Productos cu;
    M_Productos bu;

    String Columna2[] = {"ID", "Nombre", "Precio", "Cantidad Disponible", "Descripcion", "Estado"};
    DefaultTableModel Modelo2 = new DefaultTableModel(Columna2, 0);

    /**
     * Creates new form GestionInmueble
     */
    public V_GestionProductoCliente() {
        initComponents();

        bu = new M_Productos();
        cu = new C_Productos();

        cu.setIu_GestionProductoCliente(this);
        cu.ListarProductosCliente();

        C_Cliente p = new C_Cliente();

        CalcularFactura();

    }

//    public static void Deshabilitar() {
//        G_Modificadores= new JPanel();
//        G_BtnVenta = new JButton();
//        
//    }
    public void AgregarFila(String datos[]) {
        Modelo.addRow(datos);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        G_Buscar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        G_Filtro = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        G_BtnAñadir = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        G_Tabla2 = new javax.swing.JTable();
        G_BtnActualizarFactura = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        G_Tabla = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        G_Envio = new javax.swing.JLabel();
        G_SubTotal = new javax.swing.JLabel();
        G_Total = new javax.swing.JLabel();
        G_BtnEliminar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PRODUCTOS");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel3.setText("Filtro:");

        G_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_BuscarActionPerformed(evt);
            }
        });
        G_Buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                G_BuscarKeyReleased(evt);
            }
        });

        jLabel4.setText("Buscar:");

        G_Filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Identificador", "Nombre", "Precio", "Cantidad Disponible", "Descripcion", "Estado", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(G_Buscar)
                    .addComponent(G_Filtro, 0, 118, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(G_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(G_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("LISTADO DE PRODUCTOS ");

        G_BtnAñadir.setText("AÑADIR PRODUCTO AL CARRITO");
        G_BtnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G_BtnAñadirMouseClicked(evt);
            }
        });
        G_BtnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_BtnAñadirActionPerformed(evt);
            }
        });

        G_Tabla2.setModel(Modelo2);
        jScrollPane4.setViewportView(G_Tabla2);

        G_BtnActualizarFactura.setText("ACTUALIZAR FACTURA");
        G_BtnActualizarFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G_BtnActualizarFacturaMouseClicked(evt);
            }
        });
        G_BtnActualizarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_BtnActualizarFacturaActionPerformed(evt);
            }
        });
        G_BtnActualizarFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                G_BtnActualizarFacturaKeyPressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("CARRITO");

        G_Tabla.setModel(Modelo);
        jScrollPane2.setViewportView(G_Tabla);

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("FACTURA");

        G_Envio.setText("jLabel5");

        G_SubTotal.setText("jLabel5");

        G_Total.setText("jLabel5");

        G_BtnEliminar.setText("ELIMINAR PRODUCTO DEL CARRITO");
        G_BtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                G_BtnEliminarMouseClicked(evt);
            }
        });
        G_BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_BtnEliminarActionPerformed(evt);
            }
        });
        G_BtnEliminar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                G_BtnEliminarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171)
                        .addComponent(G_BtnAñadir)))
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(293, 293, 293))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(G_SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(G_Total, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                                .addComponent(G_Envio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(135, 135, 135))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(525, 525, 525))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jLabel17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(G_BtnActualizarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(769, Short.MAX_VALUE)
                    .addComponent(G_BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(125, 125, 125)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel16)
                                .addGap(70, 70, 70)
                                .addComponent(G_BtnAñadir))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(86, 86, 86)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(155, 155, 155)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(G_SubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(G_Envio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(G_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(G_BtnActualizarFactura)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(51, 51, 51))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(233, 233, 233)
                    .addComponent(G_BtnEliminar)
                    .addContainerGap(381, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void G_BuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_G_BuscarKeyReleased
        TableRowSorter<DefaultTableModel> Sorter;
        Sorter = new TableRowSorter<>(Modelo);
        G_Tabla.setRowSorter(Sorter);
        Sorter.setRowFilter(RowFilter.regexFilter(G_Buscar.getText(), G_Filtro.getSelectedIndex()));

    }//GEN-LAST:event_G_BuscarKeyReleased

    private void G_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_BuscarActionPerformed

    private void G_BtnAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G_BtnAñadirMouseClicked

    }//GEN-LAST:event_G_BtnAñadirMouseClicked

    private void G_BtnActualizarFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G_BtnActualizarFacturaMouseClicked

    }//GEN-LAST:event_G_BtnActualizarFacturaMouseClicked

    private void G_BtnActualizarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_BtnActualizarFacturaActionPerformed
        CalcularFactura();
    }//GEN-LAST:event_G_BtnActualizarFacturaActionPerformed

    private void G_BtnActualizarFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_G_BtnActualizarFacturaKeyPressed

    }//GEN-LAST:event_G_BtnActualizarFacturaKeyPressed

    private void G_BtnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_BtnAñadirActionPerformed

        int FilaSeleccionada = G_Tabla.getSelectedRow();

        if (FilaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccion un registro para agregar");
        } else if (JOptionPane.showConfirmDialog(null, "Se agregara al carrito, ¿desea continuar?") == JOptionPane.YES_OPTION) {

            if (FilaSeleccionada >= 0) {
                String Datos[] = new String[6];
                Datos[0] = G_Tabla.getValueAt(FilaSeleccionada, 0).toString();
                Datos[1] = G_Tabla.getValueAt(FilaSeleccionada, 1).toString();
                Datos[2] = G_Tabla.getValueAt(FilaSeleccionada, 2).toString();
                Datos[3] = G_Tabla.getValueAt(FilaSeleccionada, 3).toString();
                Datos[4] = G_Tabla.getValueAt(FilaSeleccionada, 4).toString();
                Datos[5] = G_Tabla.getValueAt(FilaSeleccionada, 5).toString();
                Modelo2.addRow(Datos);
            }
        }


    }//GEN-LAST:event_G_BtnAñadirActionPerformed

    private void G_BtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_G_BtnEliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_G_BtnEliminarMouseClicked

    private void G_BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_BtnEliminarActionPerformed
        int FilaSeleccionada = G_Tabla2.getSelectedRow();

        if (FilaSeleccionada == -1) {
            JOptionPane.showMessageDialog(null, "Seleccion un registro para eliminar");
        } else if (JOptionPane.showConfirmDialog(null, "Se eliminara del carrito, ¿desea continuar?") == JOptionPane.YES_OPTION) {

            if (FilaSeleccionada >= 0) {
                Modelo2.removeRow(FilaSeleccionada);
            }

        }
    }//GEN-LAST:event_G_BtnEliminarActionPerformed

    private void G_BtnEliminarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_G_BtnEliminarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_G_BtnEliminarKeyPressed

    public void CalcularFactura() {

        int Fila = 0;
        int SubTotal = 0;
        int Envio = 0;
        int Total = 0;
        int Contar = G_Tabla2.getRowCount();

        for (int i = 0; i < Contar; i++) {
            Fila = Integer.parseInt(G_Tabla2.getValueAt(i, 2).toString());
            SubTotal += Fila;
        }

        Envio = (SubTotal * 10) / 100;
        Total = Envio + SubTotal;

        G_SubTotal.setText("El SubTotal de su compra es: " + SubTotal);
        G_Envio.setText("El envio tiene un costo de: " + Envio);
        G_Total.setText("El total de su compra es: " + Total);

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton G_BtnActualizarFactura;
    private javax.swing.JButton G_BtnAñadir;
    private javax.swing.JButton G_BtnEliminar;
    private javax.swing.JTextField G_Buscar;
    private javax.swing.JLabel G_Envio;
    private javax.swing.JComboBox<String> G_Filtro;
    private javax.swing.JLabel G_SubTotal;
    private javax.swing.JTable G_Tabla;
    private javax.swing.JTable G_Tabla2;
    private javax.swing.JLabel G_Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables

}
