/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.C_Cliente;
import static Controlador.C_Cliente.UsuarioEnSesion;
import Modelo.M_Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author GUSTAVO RAMIREZ
 */
public class V_Perfil extends javax.swing.JFrame {

    C_Cliente cu;

    /**
     * Creates new form V_Perfil
     */
    public V_Perfil() {
        initComponents();
        cu = new C_Cliente();
        cu.setIu_Perfil(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        P_Contraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        P_Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        P_Apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        P_Documento = new javax.swing.JTextField();
        P_Correo = new javax.swing.JTextField();
        P_Telefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        P_Identificador = new javax.swing.JTextField();
        P_BtnEditar = new javax.swing.JButton();
        P_BtnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Teléfono");

        P_Contraseña.setEditable(false);

        jLabel3.setText("Apellido: ");

        jLabel6.setText("Correo: ");

        P_Nombre.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("PERFIL");

        P_Apellido.setEditable(false);

        jLabel4.setText("Documento:");

        P_Documento.setEditable(false);

        P_Correo.setEditable(false);

        P_Telefono.setEditable(false);

        jLabel8.setText("Contraseña:");

        jLabel14.setText("Identificador:");

        jLabel2.setText("Nombre: ");

        P_Identificador.setEditable(false);

        P_BtnEditar.setText("Editar Perfil");
        P_BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_BtnEditarActionPerformed(evt);
            }
        });

        P_BtnGuardar.setText("GUARDAR");
        P_BtnGuardar.setEnabled(false);
        P_BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_BtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(P_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(P_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(P_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(P_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(P_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel14))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(P_Contraseña, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(P_Identificador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(P_BtnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(P_BtnGuardar)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(P_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(P_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(P_Documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(P_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(P_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(P_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(P_Identificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P_BtnEditar)
                    .addComponent(P_BtnGuardar))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void P_BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_BtnEditarActionPerformed
        P_BtnEditar.setEnabled(false);
        P_BtnGuardar.setEnabled(true);
        P_Nombre.setEditable(true);
        P_Apellido.setEditable(true);
        P_Contraseña.setEditable(true);
        P_Correo.setEditable(true);
        P_Telefono.setEditable(true);

        try {
            if (JOptionPane.showConfirmDialog(null, "Se editara el registro, ¿desea continuar?") == JOptionPane.YES_OPTION) {

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccion un registro para editar");
        }

    }//GEN-LAST:event_P_BtnEditarActionPerformed

    private void P_BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_BtnGuardarActionPerformed
        if (P_Nombre.getText().isEmpty() || P_Apellido.getText().isEmpty()
                || P_Telefono.getText().isEmpty() || P_Correo.getText().isEmpty()
                || P_Contraseña.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Faltan campos por llenar");

        } else if (JOptionPane.showConfirmDialog(null, "Se actualizara el registro, ¿desea continuar?") == JOptionPane.YES_OPTION) {
            cu.ActualizarUsuario();
            this.dispose();
        }
    }//GEN-LAST:event_P_BtnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(V_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(V_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(V_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(V_Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new V_Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField P_Apellido;
    private javax.swing.JButton P_BtnEditar;
    private javax.swing.JButton P_BtnGuardar;
    private javax.swing.JPasswordField P_Contraseña;
    private javax.swing.JTextField P_Correo;
    private javax.swing.JTextField P_Documento;
    private javax.swing.JTextField P_Identificador;
    private javax.swing.JTextField P_Nombre;
    private javax.swing.JTextField P_Telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

    public void setIdentificador(String i) {
        P_Identificador.setText(i);
    }

    public void setNombre(String i) {
        P_Nombre.setText(i);
    }

    public void setApellido(String i) {
        P_Apellido.setText(i);
    }

    public void setDocumento(String i) {
        P_Documento.setText(i);
    }

    public void setCorreo(String i) {
        P_Correo.setText(i);
    }

    public void setTelefono(String i) {
        P_Telefono.setText(i);
    }

    public void setContraseña(String i) {
        P_Contraseña.setText(i);
    }

    public String getIdentificador() {
        return P_Identificador.getText();
    }

    public String getDocumento() {
        return P_Documento.getText();
    }

    public String getNombre() {
        return P_Nombre.getText();
    }

    public String getApellido() {
        return P_Apellido.getText();
    }

    public String getCorreo() {
        return P_Correo.getText();
    }

    public String getTelefono() {
        return P_Telefono.getText();
    }

    public String getContraseña() {
        return P_Contraseña.getText();

    }

    

   
    
}
