/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package realestatecalicity;

import Controlador.C_Usuario;
import Vista.V_GestionCita;
import Vista.V_GestionInmueble;
import Vista.V_GestionUsuario;
import Vista.V_Login;
import Vista.V_Registro;
import javax.swing.JFrame;

/**
 *
 * @author wdg20
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        MenuGestion.setVisible(false);//Siempre falso
        setExtendedState(MAXIMIZED_BOTH);
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MenuBarra = new javax.swing.JMenuBar();
        MenuInicio = new javax.swing.JMenu();
        I_IniciarSesion = new javax.swing.JMenuItem();
        I_CerrarSeccion = new javax.swing.JMenuItem();
        MenuGestion = new javax.swing.JMenu();
        G_Inmuebles = new javax.swing.JMenuItem();
        G_Citas = new javax.swing.JMenuItem();
        G_Usuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/realestatecalicity/Real Estate CaliCity V2 (1300 x 800 px).png"))); // NOI18N

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuInicio.setText("Inicio");

        I_IniciarSesion.setText("Iniciar Sesión");
        I_IniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_IniciarSesionActionPerformed(evt);
            }
        });
        MenuInicio.add(I_IniciarSesion);

        I_CerrarSeccion.setText("Cerrar Sesión");
        I_CerrarSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_CerrarSeccionActionPerformed(evt);
            }
        });
        MenuInicio.add(I_CerrarSeccion);

        MenuBarra.add(MenuInicio);

        MenuGestion.setText("Gestión");

        G_Inmuebles.setText("Gestionar Inmuebles");
        G_Inmuebles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_InmueblesActionPerformed(evt);
            }
        });
        MenuGestion.add(G_Inmuebles);

        G_Citas.setText("Gestionar Citas");
        G_Citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_CitasActionPerformed(evt);
            }
        });
        MenuGestion.add(G_Citas);

        G_Usuarios.setText("Gestionar Usuarios");
        G_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                G_UsuariosActionPerformed(evt);
            }
        });
        MenuGestion.add(G_Usuarios);

        MenuBarra.add(MenuGestion);

        setJMenuBar(MenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void I_IniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_IniciarSesionActionPerformed
        // CODIGO PARA INICIAR SECCION 
        V_Login Log = new V_Login(this);
        Log.setLocationRelativeTo(this);
        Log.setVisible(true);
    }//GEN-LAST:event_I_IniciarSesionActionPerformed

    private void I_CerrarSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_CerrarSeccionActionPerformed
        // CODIGO PARA CERRAR SECCION 

        Contenedor.updateUI();
        MenuGestion.setVisible(false);
        C_Usuario.UsuarioEnSesion = null;

        //SE CREA UN OBJETO DE PRINCIPAL.
        Principal v = new Principal();
        v.setVisible(true);
        dispose(); //CON EL SIPOSE SE ELIMINA LA PESTAÑA DE ATRAS PONIENDO LA INCIAL QUE VIENE SIENDO LA PRINCIPAl

    }//GEN-LAST:event_I_CerrarSeccionActionPerformed

    private void G_InmueblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_InmueblesActionPerformed
        // CODIGO PARA EL BOTON DE GESTION DE INMEBLES 
        Contenedor.removeAll();
        Contenedor.updateUI();
        //INSTANCIO EL PANEL DE LA LISTA DE LOS PEDIDOS  
        V_GestionInmueble Ges = new V_GestionInmueble();
        //Especifico el tamaño
        Ges.setSize(1340, 650);
        Contenedor.add(Ges);
        Ges.setVisible(true);
        Contenedor.validate();
    }//GEN-LAST:event_G_InmueblesActionPerformed

    private void G_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_UsuariosActionPerformed
        // TODO add your handling code here:
         Contenedor.removeAll();
        Contenedor.updateUI();
        //INSTANCIO EL PANEL DE LA LISTA DE LOS PEDIDOS  
        V_GestionUsuario Ges = new V_GestionUsuario();
        //Especifico el tamaño
        Ges.setSize(1340, 650);
        Contenedor.add(Ges);
        Ges.setVisible(true);
        Contenedor.validate();
    }//GEN-LAST:event_G_UsuariosActionPerformed

    private void G_CitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_G_CitasActionPerformed
         Contenedor.removeAll();
        Contenedor.updateUI();
        //INSTANCIO EL PANEL DE LA LISTA DE LOS PEDIDOS  
        V_GestionCita Ges = new V_GestionCita();
        //Especifico el tamaño
        Ges.setSize(1340, 650);
        Contenedor.add(Ges);
        Ges.setVisible(true);
        Contenedor.validate();
    }//GEN-LAST:event_G_CitasActionPerformed

    public void HabilitarMenu(String Nombre) {

        for (int i = 0; i < MenuBarra.getMenuCount(); i++) {
            if (MenuBarra.getMenu(i).getActionCommand().equals(Nombre)) {
                MenuBarra.getMenu(i).setVisible(true);

            }
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Contenedor;
    public static javax.swing.JMenuItem G_Citas;
    private javax.swing.JMenuItem G_Inmuebles;
    public static javax.swing.JMenuItem G_Usuarios;
    private javax.swing.JMenuItem I_CerrarSeccion;
    private javax.swing.JMenuItem I_IniciarSesion;
    private javax.swing.JMenuBar MenuBarra;
    private javax.swing.JMenu MenuGestion;
    private javax.swing.JMenu MenuInicio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
